In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

Mob = pd.read_csv("../data/processed/Mob.csv")
Inc = pd.read_csv("../data/processed/Inc_coordinates.csv")

#Add = pd.read_csv("../data/processed/Address_coordinates.csv")

Add = pd.read_csv("../data/processed/station_addresses_with_latlong_corrected.csv")
Add = Add.rename(columns={
    "lat": "Latitude",
    "long": "Longitude"
})

/tmp/ipykernel_26057/3380739445.py:7: DtypeWarning: Columns (0: DateAndTimeReturned) have mixed types. Specify dtype option on import or set low_memory=False.
  Mob = pd.read_csv("../data/processed/Mob.csv")

In [57]:
#Wanna have all the columns and  check the lists
pd.set_option('display.max_columns', None)
Add.head()

,Station Name,Borough,Address,Latitude,Longitude
0,Acton,Ealing,"27 Gunnersbury Lane, W3 8EA",51.507054,-0.276920
1,Addington,Croydon,"197-199 Lodge Lane, CR0 0QA",51.351919,-0.023621
2,Barking,Barking and Dagenham,"Alfred's Way, IG11 0BB",51.529504,0.088711
3,Barnet,Barnet,"144 Station Road, EN5 1TE",51.647255,-0.185967
4,Battersea,Wandsworth,"11 Este Road, SW11 2TL",51.467293,-0.168668

In [58]:
Mob.head()

,IncidentNumber,CalYear,HourOfCall,ResourceMobilisationId,Resource_Code,PerformanceReporting,DateAndTimeMobilised,DateAndTimeMobile,DateAndTimeArrived,TurnoutTimeSeconds,TravelTimeSeconds,AttendanceTimeSeconds,DateAndTimeLeft,DateAndTimeReturned,DeployedFromStation_Code,DeployedFromStation_Name,DeployedFromLocation,PumpOrder,PlusCode_Code,PlusCode_Description,DelayCodeId,DelayCode_Description,BoroughName,WardName
0,000004-01012021,2021,0,5769249,A321,1,NaN,NaN,NaN,48.0,133.0,181,01/01/2021 00:57,NaN,A32,Hornsey,Home Station,1,Initial,Initial Mobilisation,NaN,NaN,HARINGEY,Muswell Hill
1,000005-01012021,2021,0,5769250,F351,1,NaN,NaN,NaN,114.0,136.0,250,01/01/2021 00:18,NaN,F35,Woodford,Home Station,1,Initial,Initial Mobilisation,NaN,NaN,REDBRIDGE,MONKHAMS
2,000006-01012021,2021,0,5769251,F412,1,NaN,NaN,NaN,131.0,245.0,376,01/01/2021 00:24,NaN,F41,Dagenham,Home Station,1,Initial,Initial Mobilisation,12.0,Not held up,BARKING AND DAGENHAM,Village
3,000007-01012021,2021,0,5769252,H331,1,NaN,NaN,NaN,53.0,356.0,409,01/01/2021 00:40,NaN,H33,Wandsworth,Home Station,1,Initial,Initial Mobilisation,8.0,Traffic calming measures,WANDSWORTH,West Hill
4,000007-01012021,2021,0,5769253,G351,2,NaN,NaN,NaN,69.0,376.0,445,01/01/2021 00:29,NaN,G35,Fulham,Home Station,2,Initial,Initial Mobilisation,NaN,NaN,WANDSWORTH,West Hill

In [59]:
Inc.head()

,IncidentNumber,DateOfCall,CalYear,TimeOfCall,HourOfCall,IncidentGroup,StopCodeDescription,SpecialServiceType,PropertyCategory,PropertyType,AddressQualifier,Postcode_full,Postcode_district,UPRN,USRN,IncGeo_BoroughCode,IncGeo_BoroughName,ProperCase,IncGeo_WardCode,IncGeo_WardName,IncGeo_WardNameNew,Easting_m,Northing_m,Easting_rounded,Northing_rounded,Latitude,Longitude,FRS,IncidentStationGround,FirstPumpArriving_AttendanceTime,FirstPumpArriving_DeployedFromStation,SecondPumpArriving_AttendanceTime,SecondPumpArriving_DeployedFromStation,NumStationsWithPumpsAttending,NumPumpsAttending,PumpCount,PumpMinutesRounded,Notional Cost (£),NumCalls
0,000002-01012024,2024-01-01,2024,00:00:43,0,Special Service,Special Service,Advice Only,Dwelling,Unlicensed House in Multiple Occupation - Up t...,Correct incident location,NaN,E11,0,22822050,E09000031,WALTHAM FOREST,Waltham Forest,E05013882,CANN HALL,CANN HALL,NaN,NaN,539750,186050,51.556031,0.014432,London,Leytonstone,172.0,Stratford,289.0,Stratford,2.0,2.0,2,60,388,1.0
1,000003-01012024,2024-01-01,2024,00:01:11,0,Special Service,Special Service,No action (not false alarm),Dwelling,Purpose Built Flats/Maisonettes - 10 or more s...,Within same building,NaN,E2,0,20901068,E09000012,HACKNEY,Hackney,E05009375,HAGGERSTON,HAGGERSTON,NaN,NaN,533750,183350,51.533221,-0.073086,London,Shoreditch,332.0,Shoreditch,NaN,NaN,1.0,1.0,1,60,388,1.0
2,000007-01012024,2024-01-01,2024,00:04:21,0,False Alarm,False alarm - Good intent,NaN,Outdoor,Loose refuse,On land associated with building,SE17 3NA,SE17,10025541993,22501860,E09000028,SOUTHWARK,Southwark,E05011105,NEWINGTON,NEWINGTON,531966.0,177741.0,531950,177750,51.483237,-0.100855,London,Lambeth,521.0,Lambeth,NaN,NaN,1.0,1.0,1,60,388,1.0
3,000010-01012024,2024-01-01,2024,00:05:40,0,Special Service,Special Service,Lift Release,Dwelling,Purpose Built Flats/Maisonettes - 4 to 9 storeys,Correct incident location,NaN,W3,0,20601340,E09000009,EALING,Ealing,E05013536,SOUTH ACTON,SOUTH ACTON,NaN,NaN,520150,179350,51.500327,-0.270421,London,Acton,NaN,NaN,NaN,NaN,1.0,1.0,1,60,388,1.0
4,000011-01012024,2024-01-01,2024,00:06:32,0,Special Service,Special Service,Effecting entry/exit,Dwelling,Purpose Built Flats/Maisonettes - 10 or more s...,Correct incident location,NaN,SE3,0,20802154,E09000011,GREENWICH,Greenwich,E05014084,KIDBROOKE VILLAGE & SUTCLIFFE,KIDBROOKE VILLAGE & SUTCLIFFE,NaN,NaN,541050,175550,51.461357,0.028975,London,Lee Green,323.0,Lee Green,NaN,NaN,1.0,1.0,1,60,388,2.0

In [60]:
#check if there is a miisng name of the station
Mob["DeployedFromStation_Name"].isna()

0         False
1         False
2         False
3         False
4         False
          ...
968486    False
968487    False
968488    False
968489    False
968490    False
Name: DeployedFromStation_Name, Length: 968491, dtype: bool

In [61]:
Mobac = Mob.merge(
    Add[["Station Name", "Address", "Latitude", "Longitude"]],
    left_on="DeployedFromStation_Name",
    right_on="Station Name",
    how="left")

In [62]:
Mobac.head()

,IncidentNumber,CalYear,HourOfCall,ResourceMobilisationId,Resource_Code,PerformanceReporting,DateAndTimeMobilised,DateAndTimeMobile,DateAndTimeArrived,TurnoutTimeSeconds,TravelTimeSeconds,AttendanceTimeSeconds,DateAndTimeLeft,DateAndTimeReturned,DeployedFromStation_Code,DeployedFromStation_Name,DeployedFromLocation,PumpOrder,PlusCode_Code,PlusCode_Description,DelayCodeId,DelayCode_Description,BoroughName,WardName,Station Name,Address,Latitude,Longitude
0,000004-01012021,2021,0,5769249,A321,1,NaN,NaN,NaN,48.0,133.0,181,01/01/2021 00:57,NaN,A32,Hornsey,Home Station,1,Initial,Initial Mobilisation,NaN,NaN,HARINGEY,Muswell Hill,Hornsey,"108 Park Avenue South, N8 8LS",51.586484,-0.127589
1,000005-01012021,2021,0,5769250,F351,1,NaN,NaN,NaN,114.0,136.0,250,01/01/2021 00:18,NaN,F35,Woodford,Home Station,1,Initial,Initial Mobilisation,NaN,NaN,REDBRIDGE,MONKHAMS,Woodford,"2 Snakes Lane W, IG8 0BS",51.609446,0.023929
2,000006-01012021,2021,0,5769251,F412,1,NaN,NaN,NaN,131.0,245.0,376,01/01/2021 00:24,NaN,F41,Dagenham,Home Station,1,Initial,Initial Mobilisation,12.0,Not held up,BARKING AND DAGENHAM,Village,Dagenham,"70 Rainham Road North, Dagenham, RM10 7ES",51.559108,0.156820
3,000007-01012021,2021,0,5769252,H331,1,NaN,NaN,NaN,53.0,356.0,409,01/01/2021 00:40,NaN,H33,Wandsworth,Home Station,1,Initial,Initial Mobilisation,8.0,Traffic calming measures,WANDSWORTH,West Hill,Wandsworth,"45 West Hill Wandsworth, SW18 1RL",51.456515,-0.201450
4,000007-01012021,2021,0,5769253,G351,2,NaN,NaN,NaN,69.0,376.0,445,01/01/2021 00:29,NaN,G35,Fulham,Home Station,2,Initial,Initial Mobilisation,NaN,NaN,WANDSWORTH,West Hill,Fulham,"685 Fulham Rd, Fulham, London, SW6 5UJ",51.477930,-0.200903

In [63]:
Mobac[["Latitude", "Longitude"]].isna()

        Latitude  Longitude
0          False      False
1          False      False
2          False      False
3          False      False
4          False      False
...          ...        ...
968486     False      False
968487     False      False
968488     False      False
968489     False      False
968490     False      False

[968491 rows x 2 columns]

In [64]:
Mobac[Mobac[["Latitude", "Longitude"]].isna().any(axis=1)]["DeployedFromStation_Name"].unique()

<StringArray>
[    'Hammersmith',          'Eltham',      'Fordbridge',               nan,
   'Hertfordshire',            'Kent',          'Surrey',           'Essex',
        'Dartford',           'Esher', 'Buckinghamshire',           'Epsom',
        'Loughton',         'Watford',     'Borehamwood']
Length: 15, dtype: str

In [65]:
#Delate the Stations out of London (Out of the list of the 102)
#Wich will be the ones who are with Latitude empty
Mobac102 = Mobac.dropna(subset=["Latitude", "Longitude"])

In [66]:
Mobac102[["Latitude", "Longitude"]].isna().sum()

Latitude     0
Longitude    0
dtype: int64

In [67]:
#there are two columns with the same infromation
Mobac102 = Mobac102.drop(columns="Station Name")

In [68]:
Mobac.to_csv("../data/processed/Mobac.csv", index=False)
Mobac102.to_csv("../data/processed/Mobac102.csv", index=False)

In [69]:
Mobac102.dtypes

IncidentNumber                  str
CalYear                       int64
HourOfCall                    int64
ResourceMobilisationId        int64
Resource_Code                   str
PerformanceReporting            str
DateAndTimeMobilised        float64
DateAndTimeMobile           float64
DateAndTimeArrived          float64
TurnoutTimeSeconds          float64
TravelTimeSeconds           float64
AttendanceTimeSeconds         int64
DateAndTimeLeft                 str
DateAndTimeReturned             str
DeployedFromStation_Code        str
DeployedFromStation_Name        str
DeployedFromLocation            str
PumpOrder                     int64
PlusCode_Code                   str
PlusCode_Description            str
DelayCodeId                 float64
DelayCode_Description           str
BoroughName                     str
WardName                        str
Address                         str
Latitude                    float64
Longitude                   float64
dtype: object

In [70]:
Inc.dtypes

IncidentNumber                                str
DateOfCall                                    str
CalYear                                     int64
TimeOfCall                                    str
HourOfCall                                  int64
IncidentGroup                                 str
StopCodeDescription                           str
SpecialServiceType                            str
PropertyCategory                              str
PropertyType                                  str
AddressQualifier                              str
Postcode_full                                 str
Postcode_district                             str
UPRN                                        int64
USRN                                        int64
IncGeo_BoroughCode                            str
IncGeo_BoroughName                            str
ProperCase                                    str
IncGeo_WardCode                               str
IncGeo_WardName                               str
IncGeo_WardNameNew                            str
Easting_m                                 float64
Northing_m                                float64
Easting_rounded                             int64
Northing_rounded                            int64
Latitude                                  float64
Longitude                                 float64
FRS                                           str
IncidentStationGround                         str
FirstPumpArriving_AttendanceTime          float64
FirstPumpArriving_DeployedFromStation         str
SecondPumpArriving_AttendanceTime         float64
SecondPumpArriving_DeployedFromStation        str
NumStationsWithPumpsAttending             float64
NumPumpsAttending                         float64
PumpCount                                   int64
PumpMinutesRounded                          int64
Notional Cost (£)                           int64
NumCalls                                  float64
dtype: object

In [71]:
# after isnpection a selection of the columns is made
#mob_cols = ["IncidentNumber", "CalYear", "HourOfCall", "DateAndTimeMobilised", "DeployedFromStation_Name", "Address", "Latitude", "Longitude"]
# We presume for the same incidente the data comes from the same font, so they have to be the same therefor

#Prepare the cloumns we want to keep for the merge
mob_cols = [
    "IncidentNumber",
    "CalYear",
    "HourOfCall",
    "DateAndTimeMobilised",
    "AttendanceTimeSeconds",
    "DeployedFromStation_Name",
    "PumpOrder",
    "Latitude",
    "Longitude"]

inc_cols = [
    "IncidentNumber",
    "DateOfCall",
    "IncidentGroup",
    "SpecialServiceType",
    "PropertyCategory",
    "PropertyType",
    "IncGeo_BoroughName",
    "Latitude",
    "Longitude",
    "NumCalls",
]

#Made a new Df with only the columns
Mob_sel = Mobac102[mob_cols].copy()
Inc_sel = Inc[inc_cols].copy()

#I still need to change the name of some columns
Mob_sel = Mob_sel.rename(columns={
    "Latitude": "Station_Latitude",
    "Longitude": "Station_Longitude"})

Inc_sel = Inc_sel.rename(columns={
    "Latitude": "Incident_Latitude",
    "Longitude": "Incident_Longitude"})

In [72]:
Mob_sel.columns.unique()

Index(['IncidentNumber', 'CalYear', 'HourOfCall', 'DateAndTimeMobilised',
       'AttendanceTimeSeconds', 'DeployedFromStation_Name', 'PumpOrder',
       'Station_Latitude', 'Station_Longitude'],
      dtype='str')

In [73]:
Inc_sel.columns.unique()

Index(['IncidentNumber', 'DateOfCall', 'IncidentGroup', 'SpecialServiceType',
       'PropertyCategory', 'PropertyType', 'IncGeo_BoroughName',
       'Incident_Latitude', 'Incident_Longitude', 'NumCalls'],
      dtype='str')

In [74]:
#I prepare the Mob dfbecause of the diferents of numbers of Incident number in Inc and Mob

Mob_agg = Mob_sel.groupby("IncidentNumber").agg(
    Mob_CalYear=("CalYear", "first"),
    Mob_HourOfCall=("HourOfCall", "first"),
    DateAndTimeMobilised=("DateAndTimeMobilised", "first"),
    AttendanceTimeSeconds=("AttendanceTimeSeconds", "mean"),
    DeployedFromStation_Name=("DeployedFromStation_Name", lambda x: x.mode().iloc[0] if not x.mode().empty else None),
    PumpOrder=("PumpOrder", "max"),
    Station_Latitude=("Station_Latitude", "first"),
    Station_Longitude=("Station_Longitude", "first")
).reset_index()

#Merge of the 2 lists
Mob_Inc = Inc_sel.merge(Mob_agg, on="IncidentNumber", how="inner")

#Verification
print(Mob_Inc.shape)
print(Mob_Inc.columns.tolist())
Mob_Inc.head()

(941522, 18)
['IncidentNumber', 'DateOfCall', 'IncidentGroup', 'SpecialServiceType', 'PropertyCategory', 'PropertyType', 'IncGeo_BoroughName', 'Incident_Latitude', 'Incident_Longitude', 'NumCalls', 'Mob_CalYear', 'Mob_HourOfCall', 'DateAndTimeMobilised', 'AttendanceTimeSeconds', 'DeployedFromStation_Name', 'PumpOrder', 'Station_Latitude', 'Station_Longitude']

,IncidentNumber,DateOfCall,IncidentGroup,SpecialServiceType,PropertyCategory,PropertyType,IncGeo_BoroughName,Incident_Latitude,Incident_Longitude,NumCalls,Mob_CalYear,Mob_HourOfCall,DateAndTimeMobilised,AttendanceTimeSeconds,DeployedFromStation_Name,PumpOrder,Station_Latitude,Station_Longitude
0,000002-01012024,2024-01-01,Special Service,Advice Only,Dwelling,Unlicensed House in Multiple Occupation - Up t...,WALTHAM FOREST,51.556031,0.014432,1.0,2024,0,NaN,230.5,Stratford,2,51.543262,0.011043
1,000003-01012024,2024-01-01,Special Service,No action (not false alarm),Dwelling,Purpose Built Flats/Maisonettes - 10 or more s...,HACKNEY,51.533221,-0.073086,1.0,2024,0,NaN,332.0,Shoreditch,1,51.526211,-0.086003
2,000007-01012024,2024-01-01,False Alarm,NaN,Outdoor,Loose refuse,SOUTHWARK,51.483237,-0.100855,1.0,2024,0,NaN,521.0,Lambeth,1,51.492813,-0.121276
3,000011-01012024,2024-01-01,Special Service,Effecting entry/exit,Dwelling,Purpose Built Flats/Maisonettes - 10 or more s...,GREENWICH,51.461357,0.028975,2.0,2024,0,NaN,323.0,Lee Green,1,51.456298,0.012508
4,000012-01012024,2024-01-01,Fire,NaN,Outdoor,Road surface/pavement,ISLINGTON,51.551426,-0.110897,1.0,2024,0,NaN,208.0,Holloway,1,51.561401,-0.116207

In [75]:
#In this new df we have Stations from out of London, so the data in the Column Station-Latitude should be empty
Mob_Inc[["Station_Latitude", "Station_Longitude"]].isna().sum()

Station_Latitude     0
Station_Longitude    0
dtype: int64

In [76]:
#We dont have all. we have only the 102 London Stations

In [77]:
Mob_Inc.head()

,IncidentNumber,DateOfCall,IncidentGroup,SpecialServiceType,PropertyCategory,PropertyType,IncGeo_BoroughName,Incident_Latitude,Incident_Longitude,NumCalls,Mob_CalYear,Mob_HourOfCall,DateAndTimeMobilised,AttendanceTimeSeconds,DeployedFromStation_Name,PumpOrder,Station_Latitude,Station_Longitude
0,000002-01012024,2024-01-01,Special Service,Advice Only,Dwelling,Unlicensed House in Multiple Occupation - Up t...,WALTHAM FOREST,51.556031,0.014432,1.0,2024,0,NaN,230.5,Stratford,2,51.543262,0.011043
1,000003-01012024,2024-01-01,Special Service,No action (not false alarm),Dwelling,Purpose Built Flats/Maisonettes - 10 or more s...,HACKNEY,51.533221,-0.073086,1.0,2024,0,NaN,332.0,Shoreditch,1,51.526211,-0.086003
2,000007-01012024,2024-01-01,False Alarm,NaN,Outdoor,Loose refuse,SOUTHWARK,51.483237,-0.100855,1.0,2024,0,NaN,521.0,Lambeth,1,51.492813,-0.121276
3,000011-01012024,2024-01-01,Special Service,Effecting entry/exit,Dwelling,Purpose Built Flats/Maisonettes - 10 or more s...,GREENWICH,51.461357,0.028975,2.0,2024,0,NaN,323.0,Lee Green,1,51.456298,0.012508
4,000012-01012024,2024-01-01,Fire,NaN,Outdoor,Road surface/pavement,ISLINGTON,51.551426,-0.110897,1.0,2024,0,NaN,208.0,Holloway,1,51.561401,-0.116207

In [78]:
#save
#Sumary: Merge of Mob and Inc with the selected Columns, and all locations of the incidents, ones tahta we had and others from the rounded Eastern and Norther
#and the Coordinates of the frie_stations
Mob_Inc.to_csv("../data/processed/Mob_Inc.csv", index=False)

In [80]:
Mob_Inc["DeployedFromStation_Name"].nunique()

100

In [81]:
faltan = set(Add["Station Name"].str.strip().str.lower()) - set(Mob_Inc["DeployedFromStation_Name"].str.strip().str.lower())

Add[Add["Station Name"].str.strip().str.lower().isin(faltan)]

,Station Name,Borough,Address,Latitude,Longitude
24,Eltham Fire Station,Greenwich,"266 Eltham High St, SE9 1BA",51.450696,0.059404
34,Hammersmith Fire Station,Hammersmith and Fulham,"190-192 Shepherd's Bush Road, London, W6 7NL",51.497233,-0.223797

In [82]:
#Missing Stations in the whole list of Incidents

In [84]:
faltan = set(Add["Station Name"].str.strip().str.lower()) - set(Mob["DeployedFromStation_Name"].str.strip().str.lower())

Add[Add["Station Name"].str.strip().str.lower().isin(faltan)]

,Station Name,Borough,Address,Latitude,Longitude
24,Eltham Fire Station,Greenwich,"266 Eltham High St, SE9 1BA",51.450696,0.059404
34,Hammersmith Fire Station,Hammersmith and Fulham,"190-192 Shepherd's Bush Road, London, W6 7NL",51.497233,-0.223797